### ISSUE TITLE
Specifying missing values

### ISSUE THREAD

**Issue by willgdjones** [KamitaniLab/slir#1]
What is the best way to specify missing values here?

Thanks

**Comment by ShuntaroAoki** [comment]
slir does not support missing values in the input (i.e., it will cause an error with input including nan). So, you need to remove or impute missing values by yourself before giving them to `SparseLinearRegression.fit()` or `SparseLinearRegression.predict()`. `Imputer` in scikit-learn may be helpful for such preprocessing (see [sklearn.preprocessing.Imputer — scikit-learn 0.18.2 documentation](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Imputer.html) and [Imputing missing values before building an estimator — scikit-learn 0.18.2 documentation](http://scikit-learn.org/stable/auto_examples/missing_values.html)).
