### ISSUE TITLE
Error when importing slir

### ISSUE THREAD

**Issue by VadimDu** [KamitaniLab/slir#2]
Dear KamitaniLab,

I have successfully installed Slir package using pip3 as in your instructions.
However, when I try to import it I get the following error:
"ImportError: cannot import name 'SparseLinearRegression'"

My scikit-learn and numpy models are up to date.
I am using python3

Would greatly appreciate your advise,
Dani

**Comment by ShuntaroAoki** [comment]
Thank you for installing slir.
I've fixed the code for Python 3. Please try version 0.5.
The code passed some quick tests with Python 3 but have not been tested rigorously (since we're still using Python 2 in our lab).
